[connector]
name = "2.54mm Header"
style = "header-female"

[geometry]
pin_pitch = 10.0
padding_left = 5.0
padding_right = 5.0
height = 10.0
wall = 1.5
pin_cy = 5.0
pin_radius = 1.3
pinout_side = "bottom"
line_length = 12.0
cavity_size = 2.5
