[connector]
name = "1.27mm Header"
style = "header-female"

[geometry]
pin_pitch = 5.0
padding_left = 2.5
padding_right = 2.5
height = 5.0
wall = 0.8
pin_cy = 2.5
pin_radius = 0.65
pinout_side = "bottom"
line_length = 6.0
cavity_size = 1.25
