[connector]
name = "ST-OA (Open Air)"
style = "open-air"

[geometry]
pin_pitch = 20.0
padding_left = 12.0
padding_right = 12.0
height = 31.0
wall = 1.5
pin_cy = 15.5
pin_radius = 1.8
pinout_side = "bottom"
line_length = 20.0
cavity_size = 16.0
